Update Anaconda.c
RubyMetric/chsrc pull request #134
Opened 2024-12-07 11:38 UTC by xyx1926885268

添加了Nju、Bjtu、Pku等镜像源

2024-12-07 12:57 UTC, ccmywish requested changes
西交大的Anaconda源已经失效了。并且，西交大镜像站可能有问题，我们没有添加该镜像站。所以请删除该源。我们支持的镜像站在这个文件中：https://github.com/RubyMetric/chsrc/blob/main/src/framework/mirror.c

2024-12-07 14:12 UTC, xyx1926885268 commented
好的，我重新提交一下

2024-12-07 16:45 UTC, ccmywish commented
最后把你个人的信息填一下在这里：https://github.com/RubyMetric/chsrc/blob/main/src/recipe/ware/Anaconda.c#L5 即可。

```
 * File Authors  : Aoran Zeng <ccmywish@qq.com>
 * Contributors  : Yangmoooo <yangmoooo@outlook.com>
 *               | 你的名字 <你的邮箱>
 * Created On    : <2023-09-10>
```

2024-12-08 03:09 UTC, ccmywish commented
😥你应该在 Yangmoooo 这个贡献者的后面，再加一行，像下面这样，而不要把他删掉。

```
 * File Authors  : Aoran Zeng <ccmywish@qq.com>
 * Contributors  : Yangmoooo <yangmoooo@outlook.com>
 *               | 你的名字 <你的邮箱>
 * Created On    : <2023-09-10>
```

并且，在这里还是填中文拼音、或者英文名、或者账号名吧。因为现在所有人都是这样的：

https://github.com/RubyMetric/chsrc/blob/main/src/chsrc-main.c#L6-L20

2024-12-08 05:52 UTC, xyx1926885268 commented
好的好的，抱歉，还是第一次

2024-12-08 08:07 UTC, merged