新增在最终测速最快源后面输出源地址
RubyMetric/chsrc pull request #71
Opened 2024-09-04 06:12 UTC by shencangsheng

2024-09-04 07:17 UTC, ccmywish requested changes

2024-09-04 07:17 UTC, ccmywish commented on include/chsrc.h
> +      chsrc_succ (xy_strjoin (5, name, is, target_name, msg, " - ", sources[fast_idx].url));
这里应该是 6

2024-09-04 07:28 UTC, ccmywish commented
还有2个问题：

1. 你额外输出的其实是 “源” 的地址，和这一行开头的 “最快镜像站” 其实不是严格地语义相符

    我在这里写了 “源” 和 “镜像站” 的区别 https://github.com/RubyMetric/chsrc/blob/main/doc/Write-A-Recipe-Even-If-You-Dont-Know-C.md#%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5

2. 我知道你想要的是最快 “源” 的地址，我不知道你是否会利用这个地址做什么事情。但是 `chsrc` 有时在这一步还得不到要换源的地址具体是什么，往往需要在换源过程中拼凑出 “源” 的地址，所以这个时候，在这里输出的其实只是 “镜像站” 的地址，这种情况至少出现在 `Homebrew`, `FreeBSD` 等情况。
    
    https://github.com/RubyMetric/chsrc/blob/main/src/recipe/ware/Homebrew.c#L21-L24
    https://github.com/RubyMetric/chsrc/blob/main/src/recipe/os/BSD/FreeBSD.c#L22-L24

![image](https://github.com/user-attachments/assets/2efda784-23ca-4b18-9804-8632d072b3db)

<br>

第一点问题比较小。但是关于上述第二点，你需要做什么，你是怎么想的？

2024-09-04 07:29 UTC, ccmywish approved these changes

2024-09-04 07:44 UTC, shencangsheng commented
@ccmywish 
非常感谢，如果是这样可能与项目设计不符

其实这样做是想基于我这个 [issue](https://github.com/RubyMetric/chsrc/issues/61) ，来设计的。我的目的是希望通过获得测速最快的 `source` 来设置私有仓库使用的 `source` ，因为我阅读了部分源码看到在设置 `maven source` 时使用的是 `source.url`  ，这样做的确违背了**问题一**项目语义，当然我希望能够直接添加一个命令，例如 `./chsrc measure maven --show-source`类似的命令。很可惜我现在的 `C` 的水平有限，完整实现这样的一个命令，只能通过这种方式获取这个`source`

2024-09-04 08:03 UTC, ccmywish commented
我给 `measure` 过程单独加了一个输出，此输出不会在 `set/reset` 时出现。不知道这样是否满足你的需求。

![image](https://github.com/user-attachments/assets/d089abbf-6be6-4fcf-9bca-19c07653fe1d)

> 获得测速最快的 source 来设置私有仓库使用的 source 

理论上可行，对于 maven, NPM 这样的，`chsrc` 不存在拼凑的，都很容易做到的。但像我刚才说的 Homebrew，FreeBSD 等，这里输出的并不是你能直接用的，所以你需要对那些情况额外做一些适配。

<br>

如果你认为我上述所说的方案没问题，我就提交我新写的代码了。

2024-09-04 08:06 UTC, shencangsheng commented
@ccmywish 非常感谢，方案是没问题的。👍🏻

2024-09-04 11:55 UTC, closed without merging

2024-09-10 05:33 UTC, shencangsheng commented
https://github.com/RubyMetric/chsrc/pull/71#issuecomment-2328186132

这个修改，什么时候可以合并到mian分支并发布嘞

2024-09-12 06:46 UTC, shencangsheng commented
@ccmywish  

非常感谢功能上的支持，我在此基础上改进我得项目，这是我的新发布的版本 (easy-registry-mirror)[https://github.com/shencangsheng/easy-registry-mirror]，我先使用了 `npm` 作为实验。

如果在**项目致谢**有文案上的问题，或者违反了此项目的开源协议的应用，辛苦通知我，我将修改此项功能。

2024-09-12 08:54 UTC, ccmywish commented
@shencangsheng 

你的项目很有意义，的确是和 `chsrc` 所处理的领域是高度相关的。

我看到你在仓库中直接包含了一个 `chsrc` 的二进制文件，我觉得是没有必要的：

1. 架构问题

    你下载的只是具体针对某一架构编译的文件，比如 `x64` 的二进制，这使得 `easy-registry-mirror` 无法支持其他架构下的用户，如 arm用户，如 macOS 用户

2. 更新不及时

    因为可换的源是写死在 `chsrc` 里的，以后如果源有更新还是需要下载最新的 `chsrc`

3. 合规问题

    如果包含了二进制文件，就必须得带在仓库中包含 `chsrc` 的两个许可证：`COPYING` 和 `LICENSE-MIT.txt`，并在 README 中说明 `chsrc` 附带了这两个许可证。

<br>

## 综上

不建议把二进制`chsrc`放入仓库，你应该：

- 检测 `chsrc` 是否存在，若不存在，直接提醒用户 `chsrc` 不存在，给出链接让用户自己下载安装即可
- 或者，自行提供一种稳定的方式来下载安装 `chsrc` （可以是具体某一稳定版，也可以是最新版）

2024-09-12 09:58 UTC, shencangsheng commented
@ccmywish 

根据你的建议，我将这样修改：

* 执行命令时，会自动检查是否存在 `chsrc`，如果没有将通过 `chsrc` 的 release 下载一个对应架构的 `chsrc` 二进制

如果这样做，还需要项目中包含 `COPYING ` 和 `LICENSE-MIT.txt` 许可证吗？

2024-09-12 10:00 UTC, ccmywish commented
只要仓库里没有 `chsrc` 二进制文件，就不用包含。